/**
 * RiskShield AI - Security Alerts Center View
 */

import { stateStore } from '../state.js';
import { formatDate, formatTimeAgo, renderRiskBadge, renderStatusBadge, escapeHTML } from '../utils.js';
import { openInvestigationModal } from './investigationModal.js';

export function renderAlertsView() {
  const container = document.getElementById('main-content-viewport');
  const state = stateStore.getState();
  const alerts = state.alerts || [];

  let currentFilter = 'ALL';

  function render() {
    const totalAlerts = alerts.length;
    const criticalAlerts = alerts.filter(a => a.severity === 'CRITICAL').length;
    const investigating = alerts.filter(a => a.status === 'Under Investigation').length;
    const resolved = alerts.filter(a => a.status === 'Resolved').length;

    let filtered = alerts.filter(a => {
      if (currentFilter === 'CRITICAL') return a.severity === 'CRITICAL';
      if (currentFilter === 'HIGH') return a.severity === 'HIGH';
      if (currentFilter === 'INVESTIGATING') return a.status === 'Under Investigation';
      if (currentFilter === 'RESOLVED') return a.status === 'Resolved';
      return true;
    });

    container.innerHTML = `
      <div class="page-header">
        <div class="page-title-group">
          <h1>Security Alerts Center</h1>
          <p>Real-time security alert queue generated by AI anomaly detection modules.</p>
        </div>
      </div>

      <!-- KPI CARDS GRID -->
      <div class="kpi-grid" style="margin-bottom: 20px;">
        <div class="kpi-card primary">
          <div class="kpi-title">Total Alerts</div>
          <div class="kpi-value">${totalAlerts}</div>
        </div>
        <div class="kpi-card critical">
          <div class="kpi-title">Critical Severity</div>
          <div class="kpi-value" style="color: var(--color-critical);">${criticalAlerts}</div>
        </div>
        <div class="kpi-card medium">
          <div class="kpi-title">Under Investigation</div>
          <div class="kpi-value" style="color: var(--color-medium);">${investigating}</div>
        </div>
        <div class="kpi-card safe">
          <div class="kpi-title">Resolved Alerts</div>
          <div class="kpi-value" style="color: var(--color-safe);">${resolved}</div>
        </div>
      </div>

      <!-- FILTER TABS -->
      <div class="panel" style="margin-bottom: 20px;">
        <div class="panel-body" style="padding: 12px 20px; display: flex; gap: 8px;">
          <button class="btn btn-secondary btn-sm alert-filter-btn ${currentFilter === 'ALL' ? 'active' : ''}" data-filter="ALL">All Alerts (${totalAlerts})</button>
          <button class="btn btn-secondary btn-sm alert-filter-btn ${currentFilter === 'CRITICAL' ? 'active' : ''}" data-filter="CRITICAL">Critical (${criticalAlerts})</button>
          <button class="btn btn-secondary btn-sm alert-filter-btn ${currentFilter === 'INVESTIGATING' ? 'active' : ''}" data-filter="INVESTIGATING">Under Investigation (${investigating})</button>
          <button class="btn btn-secondary btn-sm alert-filter-btn ${currentFilter === 'RESOLVED' ? 'active' : ''}" data-filter="RESOLVED">Resolved (${resolved})</button>
        </div>
      </div>

      <!-- ALERT TABLE -->
      <div class="panel">
        <div class="panel-header">
          <span class="panel-title">Alert Queue (${filtered.length})</span>
        </div>
        <div class="table-responsive">
          <table class="data-table">
            <thead>
              <tr>
                <th>Alert ID</th>
                <th>Time</th>
                <th>Transaction ID</th>
                <th>Alert Type</th>
                <th>Severity</th>
                <th>Description</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              ${filtered.length ? filtered.map(a => `
                <tr>
                  <td class="cell-mono">${escapeHTML(a.alertId)}</td>
                  <td>${formatTimeAgo(a.timestamp)}</td>
                  <td class="cell-mono" style="color: var(--accent-cyan); cursor: pointer;" onclick="window.openTxnModal('${a.transactionId}')">
                    ${escapeHTML(a.transactionId)}
                  </td>
                  <td><strong>${escapeHTML(a.alertType)}</strong></td>
                  <td>${renderRiskBadge(a.severity)}</td>
                  <td style="max-width: 320px; font-size: 12px; color: var(--text-secondary);">${escapeHTML(a.description)}</td>
                  <td>${renderStatusBadge(a.status)}</td>
                  <td>
                    <div style="display: flex; gap: 6px;">
                      <button class="btn btn-primary btn-sm btn-investigate-alert" data-txn-id="${a.transactionId}">
                        Investigate
                      </button>
                      ${a.status !== 'Resolved' ? `
                        <button class="btn btn-success btn-sm btn-resolve-alert" data-alert-id="${a.alertId}">
                          Resolve
                        </button>
                      ` : ''}
                    </div>
                  </td>
                </tr>
              `).join('') : `
                <tr>
                  <td colspan="8" style="text-align: center; padding: 40px; color: var(--text-muted);">
                    No security alerts found matching filter "${currentFilter}".
                  </td>
                </tr>
              `}
            </tbody>
          </table>
        </div>
      </div>
    `;

    // Bind Filter Tabs
    container.querySelectorAll('.alert-filter-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        currentFilter = btn.getAttribute('data-filter');
        render();
      });
    });

    // Bind Actions
    container.querySelectorAll('.btn-investigate-alert').forEach(btn => {
      btn.addEventListener('click', () => {
        const txnId = btn.getAttribute('data-txn-id');
        if (txnId) openInvestigationModal(txnId);
      });
    });

    container.querySelectorAll('.btn-resolve-alert').forEach(btn => {
      btn.addEventListener('click', () => {
        const alertId = btn.getAttribute('data-alert-id');
        if (alertId) {
          stateStore.resolveAlert(alertId);
          render();
        }
      });
    });

    window.openTxnModal = openInvestigationModal;
  }

  render();
}
